greeting:
  message: "hello"

quarkus:
  native:
    # if needed add -H:+UnlockExperimentalVMOptions
    additional-build-args: -H:IncludeResources=venus-sample-mongodb-ds/fm-doc-process-config.xml,\
      -H:IncludeResources=venus-sample-mongodb-ds/template/document.ftl